#!/bin/sh
echo "hook I"

# Get the current version from git
# version=$(git describe --dirty)
version=$(git describe --always --dirty --long)

# Replace first dash with plus
version=$(echo $version | sed "s/-/+/")

# Save the version number to a file
echo $version > .version

# all staged python files
files=$(git diff --name-only --staged --diff-filter=d | grep ".py")

# Find all Python files in the repository
# files=$(find . -type f -name "*.py")

# Replace the __version__ variable in each file
for file in $files; do
    sed -i "s/__version__ = .*/__version__ = '$version'/" $file
    # Add the modified files to the commit
    git add $file
done

sed -i "5 s/__version__ = .*/__version__ = '$version'/" README.md
git add README.md
echo "hook F"
