#!/bin/sh

# Build the documentation
rm -rf doc/*
touch doc/.gitkeep
pdoc --html --force --output-dir doc --filter=src,tests --config latex_math=True .

# Add the modified files to the commit
git add doc/*
