name: build and publish doc

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      # - main
      - docs
    # build on any tag
    # tags:
    #   - '*'
  # manual launch build
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pdoc3
          pip install -r requirements.txt
          rm -fr doc/template-python-package
          pdoc --html --force --output-dir doc --filter=src,tests --config latex_math=True .

      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'doc/template-python-package'

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
